# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ASP-Model-CDBI-SQLite
version:      0.01
version_from: lib/Apache2/ASP/Model/CDBI/SQLite.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
